### ISSUE TITLE
The iusse about License

### ISSUE THREAD

**Issue by ZhangLujiu** [DannyVanpoucke/HIVE4-tools#5]
The license of HIVE software has expired when I run it. How can I handle this?
![image](https://user-images.githubusercontent.com/119785952/210209530-17451a31-6b01-4d4d-826e-688ed11914ab.png)

**Comment by DannyVanpoucke** [comment]
@ZhangLujiu The license was updated. It should work now. Reopen the ticket if the issue returns.
